### ISSUE TITLE
Cross platform zoomable User Interfaces (ZUI’s) with SceneGraph

### ISSUE THREAD

**Issue by JimSEOW** [wieslawsoltes/MatrixPanAndZoomDemo#1]
HI, I was looking at Urho and I found your link.
Perhaps you could be interested with the following links (especially the last one: piccolo2D.NET c# github)
https://en.wikipedia.org/wiki/Zooming_user_interface
http://c2.com/cgi/wiki?ZoomableUserInterface
http://www.cs.umd.edu/hcil/piccolo/learn/patterns.shtml
https://github.com/piccolo2d/piccolo2d.net

**Comment by wieslawsoltes** [comment]
@JimSEOW Thanks for links, I have come across those concepts some time ago, but they are far beyond this project  scope.

**Comment by JimSEOW** [comment]
@wieslawsoltes Thanks for the reply. I have used piccolo2D.NET. I wish there is something like that using SkiaSharp as the underlying drawing engine. Currently the xamarin's XAML is the most cross platform for mobile devices. it is still unclear for me which is the leading community effort in bringing WPF XAML to cross platform.

**Comment by wieslawsoltes** [comment]
@JimSEOW I use [Avalonia]( https://github.com/AvaloniaUI/Avalonia), its still in alpha. Avalonia is using SkiaSharp as one of possible drawing engines available. You can try it in action here: https://github.com/wieslawsoltes/MatrixPanAndZoomDemo/tree/master/src/Avalonia.Controls.PanAndZoom and here https://github.com/Core2D/Core2D/tree/master/src/Core2D.Avalonia.Skia (using SkiaSharp).

**Comment by JimSEOW** [comment]
@wieslawsoltes Thanks! I have yet to learn more about Avalonia. I also look at [WPF LiveCharts](https://github.com/beto-rodriguez/Live-Charts). In your view, how much effort to put Core2D.Avalonia.Skia  as the underlying drawing engine for Live-Charts?

**Comment by wieslawsoltes** [comment]
@JimSEOW With Avalonia you write drawing code once ([see Core2D Avalonia renderer example](https://github.com/Core2D/Core2D/blob/master/dependencies/Renderer.Avalonia/AvaloniaRenderer.cs)) and than just target specific platforms like [Skia](https://github.com/Core2D/Core2D/blob/master/src/Core2D.Avalonia.Skia/Program.cs#L42) or [Direct2D](https://github.com/Core2D/Core2D/blob/master/src/Core2D.Avalonia.Direct2D/Program.cs#L44). 

Regarding `Live-Charts`, I have been thinking about porting it to Avalonia, but at that time the project was evolving and was too much coupled with WPF/WinForms.

**Comment by JimSEOW** [comment]
@wieslawsoltes thanks for the [AvaloniaRenderer.cs](https://github.com/Core2D/Core2D/blob/master/dependencies/Renderer.Avalonia/AvaloniaRenderer.cs). I will take a look. I also spoke to the guys behind Live-Charts recently (less than 1 week). Using SkiaSharp is definitely of interest to them. It would be good if there is an "overview" guide (FIRST) on how to glue WPF to SkiaSharp and eventually leading to a consensus standards (SECOND). Currently, I am too new to see where the main effort is going.

**Comment by wieslawsoltes** [comment]
@JimSEOW If Live-Charts could extract core functionality to portable library and abstract the rendering and other stuff it would be much easier to port to Avalonia. Avalonia itself is not defendant on any rendering engine (its has bindings to Cairo, Direct2D, SkiaSharp) or windowing system.

**Comment by JimSEOW** [comment]
@wieslawsoltes thanks. First, I need to figure out the information you have provided. Great job for your years of work on cross platform WPF vector drawing solutions!
